/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { NavbarItem } from "./components/navbars/navbar-footer/navbar-footer";
import { NavbarItem as NavbarItem1 } from "./components/navbars/navbar-horizontal/navbar-horizontal";
export { NavbarItem } from "./components/navbars/navbar-footer/navbar-footer";
export { NavbarItem as NavbarItem1 } from "./components/navbars/navbar-horizontal/navbar-horizontal";
export namespace Components {
    interface GeneralButton {
        /**
          * Color del botón: PRIMARY, DANGER, WARNING, SUCCESS, INFO, SECONDARY
          * @default 'PRIMARY'
         */
        "color": string;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "icon": string;
        /**
          * @default 'Aceptar'
         */
        "label": string;
    }
    interface HoldExpandButton {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default 2000
         */
        "holdTime": number;
        /**
          * @default 'fas fa-save'
         */
        "icon": string;
        /**
          * @default 'Guardar'
         */
        "label": string;
    }
    interface NavbarFooter {
        /**
          * @default []
         */
        "items": NavbarItem[];
    }
    interface NavbarHorizontal {
        /**
          * Lista de items principales
          * @default []
         */
        "items": NavbarItem1[];
    }
}
declare global {
    interface HTMLGeneralButtonElement extends Components.GeneralButton, HTMLStencilElement {
    }
    var HTMLGeneralButtonElement: {
        prototype: HTMLGeneralButtonElement;
        new (): HTMLGeneralButtonElement;
    };
    interface HTMLHoldExpandButtonElement extends Components.HoldExpandButton, HTMLStencilElement {
    }
    var HTMLHoldExpandButtonElement: {
        prototype: HTMLHoldExpandButtonElement;
        new (): HTMLHoldExpandButtonElement;
    };
    interface HTMLNavbarFooterElement extends Components.NavbarFooter, HTMLStencilElement {
    }
    var HTMLNavbarFooterElement: {
        prototype: HTMLNavbarFooterElement;
        new (): HTMLNavbarFooterElement;
    };
    interface HTMLNavbarHorizontalElement extends Components.NavbarHorizontal, HTMLStencilElement {
    }
    var HTMLNavbarHorizontalElement: {
        prototype: HTMLNavbarHorizontalElement;
        new (): HTMLNavbarHorizontalElement;
    };
    interface HTMLElementTagNameMap {
        "general-button": HTMLGeneralButtonElement;
        "hold-expand-button": HTMLHoldExpandButtonElement;
        "navbar-footer": HTMLNavbarFooterElement;
        "navbar-horizontal": HTMLNavbarHorizontalElement;
    }
}
declare namespace LocalJSX {
    interface GeneralButton {
        /**
          * Color del botón: PRIMARY, DANGER, WARNING, SUCCESS, INFO, SECONDARY
          * @default 'PRIMARY'
         */
        "color"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "icon"?: string;
        /**
          * @default 'Aceptar'
         */
        "label"?: string;
    }
    interface HoldExpandButton {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default 2000
         */
        "holdTime"?: number;
        /**
          * @default 'fas fa-save'
         */
        "icon"?: string;
        /**
          * @default 'Guardar'
         */
        "label"?: string;
    }
    interface NavbarFooter {
        /**
          * @default []
         */
        "items"?: NavbarItem[];
    }
    interface NavbarHorizontal {
        /**
          * Lista de items principales
          * @default []
         */
        "items"?: NavbarItem1[];
    }
    interface IntrinsicElements {
        "general-button": GeneralButton;
        "hold-expand-button": HoldExpandButton;
        "navbar-footer": NavbarFooter;
        "navbar-horizontal": NavbarHorizontal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "general-button": LocalJSX.GeneralButton & JSXBase.HTMLAttributes<HTMLGeneralButtonElement>;
            "hold-expand-button": LocalJSX.HoldExpandButton & JSXBase.HTMLAttributes<HTMLHoldExpandButtonElement>;
            "navbar-footer": LocalJSX.NavbarFooter & JSXBase.HTMLAttributes<HTMLNavbarFooterElement>;
            "navbar-horizontal": LocalJSX.NavbarHorizontal & JSXBase.HTMLAttributes<HTMLNavbarHorizontalElement>;
        }
    }
}
