/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GeneralButton {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default 'Aceptar'
         */
        "label": string;
    }
}
declare global {
    interface HTMLGeneralButtonElement extends Components.GeneralButton, HTMLStencilElement {
    }
    var HTMLGeneralButtonElement: {
        prototype: HTMLGeneralButtonElement;
        new (): HTMLGeneralButtonElement;
    };
    interface HTMLElementTagNameMap {
        "general-button": HTMLGeneralButtonElement;
    }
}
declare namespace LocalJSX {
    interface GeneralButton {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default 'Aceptar'
         */
        "label"?: string;
    }
    interface IntrinsicElements {
        "general-button": GeneralButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "general-button": LocalJSX.GeneralButton & JSXBase.HTMLAttributes<HTMLGeneralButtonElement>;
        }
    }
}
