/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { NavbarItem } from "./components/navbars/navbar-footer/navbar-footer";
import { NavbarItem as NavbarItem1 } from "./components/navbars/navbar-horizontal/navbar-horizontal";
export { NavbarItem } from "./components/navbars/navbar-footer/navbar-footer";
export { NavbarItem as NavbarItem1 } from "./components/navbars/navbar-horizontal/navbar-horizontal";
export namespace Components {
    interface CardGeneral {
        /**
          * Alto del card
          * @default 'auto'
         */
        "height": string;
        /**
          * Ancho del card
          * @default '300px'
         */
        "width": string;
    }
    interface DonutRadio {
        /**
          * @default 'PRIMARY'
         */
        "color": string;
        "label": string;
        "name": string;
    }
    interface GeneralButton {
        /**
          * Color del botón: PRIMARY, DANGER, WARNING, SUCCESS, INFO, SECONDARY
          * @default 'PRIMARY'
         */
        "color": string;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "icon": string;
        /**
          * @default 'Aceptar'
         */
        "label": string;
    }
    interface HoldExpandButton {
        /**
          * Color del botón: PRIMARY, DANGER, WARNING, SUCCESS, INFO, SECONDARY
          * @default 'PRIMARY'
         */
        "color": string;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * Tiempo de presión en ms
          * @default 1000
         */
        "holdTime": number;
        /**
          * @default 'fas fa-save'
         */
        "icon": string;
        /**
          * @default 'Guardar'
         */
        "label": string;
    }
    interface NavbarFooter {
        /**
          * @default []
         */
        "items": NavbarItem[];
    }
    interface NavbarHorizontal {
        /**
          * Lista de items principales
          * @default []
         */
        "items": NavbarItem1[];
    }
    interface TableGeneral {
        /**
          * Columnas: { key: string, label: string, color }
          * @default []
         */
        "columns": any[] | string;
        /**
          * Datos: arreglo de objetos
          * @default []
         */
        "data": any[] | string;
    }
}
export interface NavbarFooterCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNavbarFooterElement;
}
declare global {
    interface HTMLCardGeneralElement extends Components.CardGeneral, HTMLStencilElement {
    }
    var HTMLCardGeneralElement: {
        prototype: HTMLCardGeneralElement;
        new (): HTMLCardGeneralElement;
    };
    interface HTMLDonutRadioElement extends Components.DonutRadio, HTMLStencilElement {
    }
    var HTMLDonutRadioElement: {
        prototype: HTMLDonutRadioElement;
        new (): HTMLDonutRadioElement;
    };
    interface HTMLGeneralButtonElement extends Components.GeneralButton, HTMLStencilElement {
    }
    var HTMLGeneralButtonElement: {
        prototype: HTMLGeneralButtonElement;
        new (): HTMLGeneralButtonElement;
    };
    interface HTMLHoldExpandButtonElement extends Components.HoldExpandButton, HTMLStencilElement {
    }
    var HTMLHoldExpandButtonElement: {
        prototype: HTMLHoldExpandButtonElement;
        new (): HTMLHoldExpandButtonElement;
    };
    interface HTMLNavbarFooterElementEventMap {
        "navigate": string;
    }
    interface HTMLNavbarFooterElement extends Components.NavbarFooter, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNavbarFooterElementEventMap>(type: K, listener: (this: HTMLNavbarFooterElement, ev: NavbarFooterCustomEvent<HTMLNavbarFooterElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNavbarFooterElementEventMap>(type: K, listener: (this: HTMLNavbarFooterElement, ev: NavbarFooterCustomEvent<HTMLNavbarFooterElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNavbarFooterElement: {
        prototype: HTMLNavbarFooterElement;
        new (): HTMLNavbarFooterElement;
    };
    interface HTMLNavbarHorizontalElement extends Components.NavbarHorizontal, HTMLStencilElement {
    }
    var HTMLNavbarHorizontalElement: {
        prototype: HTMLNavbarHorizontalElement;
        new (): HTMLNavbarHorizontalElement;
    };
    interface HTMLTableGeneralElement extends Components.TableGeneral, HTMLStencilElement {
    }
    var HTMLTableGeneralElement: {
        prototype: HTMLTableGeneralElement;
        new (): HTMLTableGeneralElement;
    };
    interface HTMLElementTagNameMap {
        "card-general": HTMLCardGeneralElement;
        "donut-radio": HTMLDonutRadioElement;
        "general-button": HTMLGeneralButtonElement;
        "hold-expand-button": HTMLHoldExpandButtonElement;
        "navbar-footer": HTMLNavbarFooterElement;
        "navbar-horizontal": HTMLNavbarHorizontalElement;
        "table-general": HTMLTableGeneralElement;
    }
}
declare namespace LocalJSX {
    interface CardGeneral {
        /**
          * Alto del card
          * @default 'auto'
         */
        "height"?: string;
        /**
          * Ancho del card
          * @default '300px'
         */
        "width"?: string;
    }
    interface DonutRadio {
        /**
          * @default 'PRIMARY'
         */
        "color"?: string;
        "label": string;
        "name": string;
    }
    interface GeneralButton {
        /**
          * Color del botón: PRIMARY, DANGER, WARNING, SUCCESS, INFO, SECONDARY
          * @default 'PRIMARY'
         */
        "color"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "icon"?: string;
        /**
          * @default 'Aceptar'
         */
        "label"?: string;
    }
    interface HoldExpandButton {
        /**
          * Color del botón: PRIMARY, DANGER, WARNING, SUCCESS, INFO, SECONDARY
          * @default 'PRIMARY'
         */
        "color"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Tiempo de presión en ms
          * @default 1000
         */
        "holdTime"?: number;
        /**
          * @default 'fas fa-save'
         */
        "icon"?: string;
        /**
          * @default 'Guardar'
         */
        "label"?: string;
    }
    interface NavbarFooter {
        /**
          * @default []
         */
        "items"?: NavbarItem[];
        "onNavigate"?: (event: NavbarFooterCustomEvent<string>) => void;
    }
    interface NavbarHorizontal {
        /**
          * Lista de items principales
          * @default []
         */
        "items"?: NavbarItem1[];
    }
    interface TableGeneral {
        /**
          * Columnas: { key: string, label: string, color }
          * @default []
         */
        "columns"?: any[] | string;
        /**
          * Datos: arreglo de objetos
          * @default []
         */
        "data"?: any[] | string;
    }
    interface IntrinsicElements {
        "card-general": CardGeneral;
        "donut-radio": DonutRadio;
        "general-button": GeneralButton;
        "hold-expand-button": HoldExpandButton;
        "navbar-footer": NavbarFooter;
        "navbar-horizontal": NavbarHorizontal;
        "table-general": TableGeneral;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "card-general": LocalJSX.CardGeneral & JSXBase.HTMLAttributes<HTMLCardGeneralElement>;
            "donut-radio": LocalJSX.DonutRadio & JSXBase.HTMLAttributes<HTMLDonutRadioElement>;
            "general-button": LocalJSX.GeneralButton & JSXBase.HTMLAttributes<HTMLGeneralButtonElement>;
            "hold-expand-button": LocalJSX.HoldExpandButton & JSXBase.HTMLAttributes<HTMLHoldExpandButtonElement>;
            "navbar-footer": LocalJSX.NavbarFooter & JSXBase.HTMLAttributes<HTMLNavbarFooterElement>;
            "navbar-horizontal": LocalJSX.NavbarHorizontal & JSXBase.HTMLAttributes<HTMLNavbarHorizontalElement>;
            "table-general": LocalJSX.TableGeneral & JSXBase.HTMLAttributes<HTMLTableGeneralElement>;
        }
    }
}
